const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=__dirname,output=path.join(root,'standalone');fs.mkdirSync(output,{recursive:true});
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const fmt=n=>n.toLocaleString('en-US'),nparams=w=>w.shape.reduce((s,n)=>s*n,1)*w.count;
const baseCss=fs.readFileSync(path.join(root,'viewer-ui.css'),'utf8');
const baseJs=fs.readFileSync(path.join(root,'viewer-ui.js'),'utf8');
const favicon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="7" fill="#334add"/><path d="M8 8h16M8 16h16M8 24h16M16 8v16" stroke="white" stroke-width="3"/><circle cx="16" cy="16" r="4" fill="white"/></svg>';
function weightsTable(weights){return `<div class="table-scroll"><table><thead><tr><th>权重 / 参数</th><th>形状</th><th>重复</th><th>合计</th></tr></thead><tbody>${weights.map(w=>`<tr><td>${esc(w.name)}${w.note?`<small>${esc(w.note)}</small>`:''}</td><td><code>[${w.shape.join(', ')}]</code></td><td>${fmt(w.count)}</td><td>${fmt(nparams(w))}</td></tr>`).join('')}</tbody></table></div>`;}
function flow(steps,cls=''){return `<div class="flow ${cls}">${(steps||[]).map(s=>`<div class="op"><strong>${esc(s.label)}</strong>${s.shape?`<code>${esc(s.shape)}</code>`:''}${s.detail?`<small>${esc(s.detail)}</small>`:''}</div>`).join('<span class="flow-arrow" aria-hidden="true">↓</span>')}</div>`;}
const models=[];
for(const file of fs.readdirSync(path.join(root,'models')).filter(f=>f.endsWith('.json'))){
 const m=JSON.parse(fs.readFileSync(path.join(root,'models',file),'utf8'));models.push(m);
 const ids=m.modules.map(x=>x.id);assert.equal(new Set(ids).size,ids.length,m.id+' duplicate module id');
 const allWeights=m.modules.flatMap(x=>x.weights||[]);
 for(const w of allWeights){assert(w.shape.length&&w.shape.every(x=>Number.isInteger(x)&&x>0),m.id+' invalid shape '+w.name);assert(Number.isInteger(w.count)&&w.count>0);}
 const total=allWeights.reduce((s,w)=>s+nparams(w),0);assert.equal(total,m.totalParams,m.id+' total mismatch');
 const c=m.color;assert(/^#[a-f\d]{6}$/i.test(c));
 const sourceLinks=arr=>`<ul class="source-links">${(arr||[]).map(i=>m.sources[i]).filter(Boolean).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)}</a><small>${esc(s.usedFor)}</small></li>`).join('')}</ul>`;
 function renderModule(mod){
  const relatives=m.modules.filter(x=>x.parentId===mod.id);
  const parents=m.connections.filter(x=>x[1]===mod.id).map(x=>m.modules.find(z=>z.id===x[0])).filter(Boolean);
  const graphIn=parents.length?`<p class="input-sources">输入来自 ${parents.map(p=>`<button type="button" data-select="${esc(p.id)}">${esc(p.name)}</button>`).join(' ')}</p>`:'';
  const branches=mod.branches?.length?`<div class="branches">${mod.branches.map(b=>`<section><h3>${esc(b.name)}</h3>${flow(b.steps)}</section>`).join('')}</div>`:'';
  const related=relatives.length?`<div class="related">${relatives.map(r=>`<button type="button" data-select="${esc(r.id)}">展开 ${esc(r.name)}</button>`).join('')}</div>`:'';
  return `<p class="module-summary">${esc(mod.summary)}</p>${graphIn}${branches}${flow(mod.flow)}${related}${mod.notes?.length?`<ul class="notes">${mod.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul>`:''}${mod.weights?.length?`<h3>权重形状与重复次数 <small>本模块合计 ${fmt(mod.weights.reduce((s,w)=>s+nparams(w),0))}</small></h3>${weightsTable(mod.weights)}`:'<p class="count-note">本节点的参数已在子模块中列账，或本身不含可学习权重；不重复相加。</p>'}${sourceLinks(mod.sourceIds)}`;
 }
 const cats={};for(const w of allWeights)cats[w.category]=(cats[w.category]||0)+nparams(w);
 const ledger={id:'parameter-ledger',name:'参数总账',repeat:fmt(total),kind:'aux',body:`<p class="total">${fmt(total)}<small>${esc(m.scope)}</small></p><div class="table-scroll"><table><thead><tr><th>参数分组</th><th>总参数</th><th>比例</th></tr></thead><tbody>${Object.entries(cats).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${fmt(v)}</td><td>${(v/total*100).toFixed(4)}%</td></tr>`).join('')}</tbody></table></div><ul class="notes">${(m.notes||[]).map(n=>`<li>${esc(n)}</li>`).join('')}</ul><details><summary>全部 ${allWeights.length} 种权重条目</summary>${weightsTable(allWeights)}</details>`};
 const evidence={id:'source-evidence',name:'来源与校对边界',repeat:m.checkpoint,kind:'aux',body:`<p>${esc(m.scope)}</p><dl><dt>模型 / checkpoint</dt><dd>${esc(m.checkpoint)}</dd><dt>许可证</dt><dd>${esc(m.license)}</dd><dt>核对方法</dt><dd>${esc(m.checks.method)}</dd><dt>已核对</dt><dd>${esc(m.checks.verified)}</dd><dt>未核对 / 限制</dt><dd>${esc(m.checks.notVerified)}</dd></dl>${sourceLinks(m.sources.map((_,i)=>i))}<p class="date">本图是固定版本的结构快照，不随同名模型更新。参数个数不是文件字节数或运行显存。</p>`};
 const modules=[...m.modules,ledger,evidence];
 const nav=id=>{const mod=modules.find(x=>x.id===id);return `<button type="button" class="module ${mod.kind==='main'?'':'mini'}" data-select="${esc(id)}" aria-expanded="false" aria-controls="detail-${esc(id)}"><span>${esc(mod.name)}</span><small>${esc(mod.repeat)}</small></button>`;};
 const mains=m.modules.filter(x=>x.kind==='main'),inserted=new Set();
 let trunk='';for(let i=0;i<mains.length;i++){const mod=mains[i];trunk+=nav(mod.id);inserted.add(mod.id);const children=m.modules.filter(x=>x.kind==='detail'&&x.parentId===mod.id);if(children.length){trunk+=`<div class="children">${children.map(ch=>{inserted.add(ch.id);return nav(ch.id)}).join('')}</div>`;}trunk+='<div class="trunk-gap"></div>';}
 const rest=modules.filter(x=>!inserted.has(x.id));
 const cards=modules.map(mod=>`<article id="detail-${esc(mod.id)}" class="detail" data-module="${esc(mod.id)}" hidden><div class="detail-title"><div><span class="eyebrow">${esc(mod.repeat)}</span><h2>${esc(mod.name)}</h2></div><button type="button" class="close" data-close="${esc(mod.id)}" aria-label="收起${esc(mod.name)}">收起 ×</button></div><div class="detail-body">${mod.body||renderModule(mod)}</div></article>`).join('');
 const css=baseCss.replaceAll('#4d6bfe',c).replaceAll('#6f88ff',c)+`
 :root{--brand:${c};--brand-ink:color-mix(in srgb,var(--brand),#17263c 32%);--brand-wash:color-mix(in srgb,var(--brand) 7%,white)}body{font-size:16px}header h1,nav h2,.detail h2,.total{color:var(--brand-ink)!important}.tools button:first-child,.module.active{background:var(--brand-ink);border-color:var(--brand-ink)}.module,.related button,.input-sources button{color:var(--brand-ink);background:var(--brand-wash);border-color:color-mix(in srgb,var(--brand) 22%,white)}.module.active{color:white}.module.active small{color:#fff}.module small,.eyebrow{color:color-mix(in srgb,var(--brand),#45516c 50%)}.module[aria-expanded=true]:not(.active){border-color:var(--brand);background:var(--brand-wash)}.detail-title,th,.flow .op{background:var(--brand-wash)}a,summary,.close,.detail h3,.flow-arrow{color:var(--brand-ink)}nav{width:390px;padding:22px 27px}#detail-region{left:455px}.module{transition:box-shadow .2s,transform .2s}.module span{font-size:14px}.module small,.mini small{font-size:12px}.mini span{font-size:13px}header p,.status{font-size:13px}nav>p{font-size:12px}.module{position:relative;z-index:2;min-height:48px}.children{position:relative;z-index:2;flex-wrap:wrap}.children .mini{flex-basis:135px}.aux{position:relative;z-index:2}.trunk-gap{height:17px}.flow{max-width:760px}.flow .op{padding:17px;border-color:color-mix(in srgb,var(--brand) 20%,white)}.op strong,.op code,.op small{display:block}.op code{font-size:15px;margin:6px 0;white-space:normal}.op small{font-size:13px;color:#60708b}.branches{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}.branches h3{font-size:16px;text-align:center}.branches .flow{margin-top:8px}.related button{font-size:14px}h3 small{display:block;font-size:13px;font-weight:400}.notes li{margin:9px 0;color:#586c87}.source-links{border-top:1px solid #e5e9f2;padding-top:15px;font-size:13px}.source-links small,td small{display:block;color:#718098;margin-top:5px;font-size:12px}table{font-size:14px}td{overflow-wrap:anywhere}td:first-child{max-width:420px}td code{font-size:13px}td:nth-child(2){white-space:nowrap}.input-sources{font-size:13px}.input-sources button{font-size:13px;padding:4px 7px;border:1px solid #dce3f1;border-radius:5px;margin:3px}.count-note,.date{font-size:13px}.model-home{font-size:12px;letter-spacing:0;text-decoration:none;color:#62718f;display:inline-block;margin-bottom:3px}header h1{font-size:23px}header{height:124px}.layout{height:calc(100dvh - 146px)}.facts{display:flex;gap:8px;flex-wrap:wrap;margin-top:5px}.facts span{font-size:11px;color:#71819d}dl{display:grid;grid-template-columns:110px 1fr;gap:12px}dt{color:#7c8ba4;font-size:13px}dd{margin:0;overflow-wrap:anywhere}#trunk-links{position:absolute;left:0;top:0;width:100%;pointer-events:none;z-index:1;overflow:visible}#trunk-links path{fill:none;stroke:var(--brand);stroke-width:1.2;opacity:.4}#trunk-links path.long-edge{stroke-dasharray:3 4}#trunk-links circle{fill:var(--brand);opacity:.4}
 @media(max-width:1150px) and (min-width:761px){nav{width:320px;padding:18px}#detail-region{left:370px}}@media(max-width:760px){header{height:auto}.layout{height:auto}.layout nav{width:min(390px,100%)}#detail-region{left:auto}.branches{grid-template-columns:1fr}.facts{display:none}header h1{font-size:21px}dl{grid-template-columns:1fr;gap:3px}dd{margin-bottom:12px}table{font-size:13px}}
 `;
 const connections=JSON.stringify(m.connections).replace(/</g,'\\u003c');
 const js=baseJs+`
 const trunkEdges=${connections};const trunkSvg=document.getElementById('trunk-links');
 function drawTrunk(){const nr=navEl.getBoundingClientRect(),h=navEl.scrollHeight;trunkSvg.style.height=h+'px';trunkSvg.setAttribute('viewBox','0 0 '+nr.width+' '+h);let s='';for(const [a,b] of trunkEdges){const x=navEl.querySelector('[data-select="'+a+'"]'),y=navEl.querySelector('[data-select="'+b+'"]');if(!x||!y)continue;const p=x.getBoundingClientRect(),q=y.getBoundingClientRect();const x1=p.left+p.width/2-nr.left,y1=p.bottom-nr.top+navEl.scrollTop,x2=q.left+q.width/2-nr.left,y2=q.top-nr.top+navEl.scrollTop;const near=Math.abs(y2-y1)<40;const d=near?'M '+x1+' '+y1+' L '+x2+' '+y2:'M '+(p.left-nr.left)+' '+(p.top+p.height/2-nr.top+navEl.scrollTop)+' H 12 V '+(q.top+q.height/2-nr.top+navEl.scrollTop)+' H '+(q.left-nr.left);s+='<path class="'+(near?'':'long-edge')+'" d="'+d+'"/>';if(near)s+='<circle cx="'+x2+'" cy="'+(y2-4)+'" r="2"/>';}trunkSvg.innerHTML=s;}
 new ResizeObserver(drawTrunk).observe(navEl);window.addEventListener('resize',drawTrunk);drawTrunk();
 `;
 const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(m.tagline)}"><title>${esc(m.name)} · 🧩 开源 AI 模型结构可视化</title><link rel="icon" href="data:image/svg+xml,${encodeURIComponent(favicon)}"><style>${css}</style></head><body><header><div><a class="model-home" href="../index.html">🧩 开源 AI 模型结构可视化</a><h1>${esc(m.name)}</h1><p>${esc(m.company)} · ${esc(m.family)} · ${esc(m.totalLabel)}</p></div><div class="tools"><button type="button" id="expand-all">全部展开</button><button type="button" id="collapse-all">全部收起</button></div></header><div class="layout"><svg id="links-layer" aria-hidden="true"></svg><nav aria-label="主干总览"><svg id="trunk-links" aria-hidden="true"></svg><h2>主干总览</h2><p>点击展开构造 · 权重维度 [out,in]</p>${trunk}<div class="aux">${rest.map(x=>nav(x.id)).join('')}</div><p class="hint">参数按本页明确的范围统计；共享权重只计一次。</p></nav><main id="detail-region"><p id="status" class="status" role="status" aria-live="polite"></p>${cards}</main></div><script>${js}</script></body></html>`;
 fs.writeFileSync(path.join(output,m.id+'.html'),html);
}
fs.writeFileSync(path.join(root,'page-build.json'),JSON.stringify({time:new Date().toISOString(),models:models.map(m=>({id:m.id,totalParams:m.totalParams,modules:m.modules.length,output:m.id+'.html'}))},null,2));
console.log('Built standalone pages:',models.map(m=>m.id).join(', '));
